<link rel="alternate" hreflang="x-default" href="/">
<link rel="alternate" hreflang="en" href="/">
<link rel="alternate" hreflang="vi" href="/vn/">
<link rel="alternate" hreflang="tr" href="/tr/">
<link rel="alternate" hreflang="id-ID" href="/ID/">
<link rel="alternate" hreflang="fr" href="/fr/">
<link rel="alternate" hreflang="pt" href="/pt/">
<link rel="alternate" hreflang="es" href="/es/">
<link rel="alternate" hreflang="ms" href="/ms/">
<link rel="alternate" hreflang="ko" href="/ko/">
<link rel="alternate" hreflang="ja" href="/ja/">
<link rel="alternate" hreflang="jv" href="/jv/">
<link rel="alternate" hreflang="de" href="/de/">
<link rel="alternate" hreflang="it" href="/it/">
<link rel="alternate" hreflang="ko" href="/ko/">
<link rel="alternate" hreflang="in" href="/in/">